# Generated by Django 5.2.6 on 2025-09-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('Battery', models.FloatField(blank=True, null=True)),
                ('Humidity', models.FloatField(blank=True, null=True)),
                ('Motion', models.IntegerField(blank=True, null=True)),
                ('Temperature', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
